global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "app"
    metrics_path: /metrics
    dns_sd_configs:
      - names:
          - app
        type: A
        port: 5000

  - job_name: "nginx-exporter"
    static_configs:
      - targets: ["nginx-exporter:9113"]

  - job_name: "redis-exporter"
    static_configs:
      - targets: ["redis-exporter:9121"]

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090'] 